spring:
    application:
        name: PaymentService
    datasource:
        url: jdbc:postgresql://accounts-postgres:5432/acc_db
        username: acc
        password: acc
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    liquibase:
        enabled: false
    kafka:
        bootstrap-servers: kafka:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

grpc:
    server:
        address: 0.0.0.0
        port: 9090
        negotiationType: PLAINTEXT