spring:
    application:
        name: PaymentService
    datasource:
        url: jdbc:postgresql://accounts-postgres:5432/acc_db
        username: acc
        password: acc
        driver-class-name: org.postgresql.Driver
    jpa:
        how-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    liquibase:
        enabled: false

grpc:
    server:
        address: 0.0.0.0
        port: 9090
        negotiationType: PLAINTEXT