spring:
    application:
        name: OrdersService
    datasource:
        url: jdbc:postgresql://orders-postgres:5432/orders_db
        username: orders
        password: orders
        driver-class-name: org.postgresql.Driver
    jpa:
        how-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    liquibase:
        enabled: false

    kafka:
        bootstrap-servers: kafka:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    redis:
        host: localhost
        port: 6379

grpc:
    server:
        address: 0.0.0.0
        port: 9090
        negotiationType: PLAINTEXT