spring:
    application:
        name: OrdersService
    datasource:
        url: jdbc:postgresql://orders-postgres:5432/orders_db
        username: orders
        password: orders
        driver-class-name: org.postgresql.Driver
    jpa:
        how-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    liquibase:
        enabled: false

    kafka:
        bootstrap-servers: localhost:29092
        properties:
            security.protocol: PLAINTEXT
        admin:
            auto-create-topics: true
        consumer:
            group-id: orders
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "ordersapp.ordersservice,java.util,java.lang"
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
grpc:
    server:
        address: 0.0.0.0
        port: 9090
        negotiationType: PLAINTEXT